env:
  global:
    - CC_TEST_REPORTER_ID=1a7c1a70e25849ae1f31d5999649d47b03e6ebc8e27b7cdacaed03e8ea2144a0
language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn test -- --coverage
  - yarn build
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi.trav